@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package therealfarfetchd.qcommon.architect.model.value;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;