@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package therealfarfetchd.qcommon.architect.client.dynrender.shaderbuilder;

import javax.annotation.ParametersAreNonnullByDefault;

import therealfarfetchd.qcommon.MethodsReturnNonnullByDefault;