@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package therealfarfetchd.qcommon.architect.model;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;